name:               "Gokhan Derala"
description:        "Software Developer"

url:                "gokhanderala.com"
author:             "Gokhan Derala"
email:              "gderala@gmail.com"
gravatar_hash:      "1522b62cad68b5ad05099cdfa272b6fc"
email:              "gderala@gmail.com"
github:             "deralation"
linkedin:           "gokhanderala"
lewagon:            "https://www.lewagon.com/"
college:            "https://www.comu.edu.tr/en/"
yoyo:               "http://driveyoyo.com/"
adphorus:           "https://adphorus.com"
github.repository: "deralation.github.io"

disqus_shortname:   "deralation"

background:         ""

paginate:           5
paginate_path:      "/page:num/"  

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/"
  - name:           "Portolio"
    href:           "/portfolio/"
  - name:           "CV"
    href:           "/cv/"
  - name:           "Github"
    href:           "http://github.com/deralation"
  - name:           "Linkedin"
    href:           "http://linkedin.com/in/gokhanderala" 

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate